name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - rc
  workflow_dispatch:

jobs:
  autotests:
    name: Run tests
    strategy:
      matrix:
        node: ['18']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run Test
        run: npm run test
        continue-on-error: true
